del /q /s *.dcu
del /q /s *.identcache
del /q /s *.local
del /q /s *.rsm
del /q /s *.dsk
del /q /s *.~dsk
rmdir /Q /S .\Samples\__history
rmdir /Q /S .\Samples\__recovery
rmdir /Q /S .\__history
rmdir /Q /S .\__recovery
del /q /s Win32\LibPhonenumber.exe
del /q /s Win32\*.config
del /q /s Win32\*.xml
del /q /s Win64\LibPhonenumber.exe
del /q /s Win64\*.config
del /q /s Win64\*.xml