del /q /s *.dcu
del /q /s *.identcache
del /q /s *.local
del /q /s *.dsk
del /q /s *.~dsk
rmdir /Q /S .\Samples\__history
rmdir /Q /S .\Samples\__recovery
rmdir /Q /S .\__history
rmdir /Q /S .\__recovery